import type { AiStreamEvent, DailyNote, MealEntry, MoodEntry } from '@knowledge-base/contracts'
import { apiClient, isApiClientAbort } from '../../api-client'
import { todayLocalDate } from '../mood/mood-levels'
import { startMidnightAutoGenerate } from '../daily-summary/daily-summary-auto'

/**
 * 今日饮食推荐自动生成：跨天检测 + 幂等保护。
 * - 当天已有推荐则不触发；
 * - AI 未配置则静默降级（不调用）；
 * - 生成失败不重试（避免重复消耗），返回 failed 供卡片显示手动按钮。
 * 生成提示词走全局知识（手记/事项/复盘/方法/三餐/情绪），不限于饮食。
 */

/** 角色指令：饮食营养师，只针对饮食，不做整体状态分析。 */
const DIET_PROMPT = [
  '你是顶级营养师，我的身高是178cm，体重是81kg。',
  '请根据目前时间、最近的饮食习惯，以及我的今日饮食，来分析今日剩余时间的饮食，并给出建议。',
  '尽量简单垂直点说明；推荐饮食时推荐一些简单好记的推荐，别种类太多；',
  '末尾不需要问句钩子；结论时不要重复我的基础信息（如身高体重）。',
].join('\n')

const LAST_SEEN_DATE_KEY = 'marumaru.daily-diet.last-seen-date'
let documentStartKey = todayLocalDate()
const generateStartedRef = { current: false }

function writeLastSeenDate(date: string): void {
  try { localStorage.setItem(LAST_SEEN_DATE_KEY, date) } catch { /* ignore */ }
}

export interface DailyDietAutoResult {
  /** 本次是否真正调用并生成了内容（写入 daily_diet_recommendations） */
  generated: boolean
  /** 是否发现 AI 未配置（静默失败） */
  aiUnavailable: boolean
  /** 生成失败（不用于展示，仅卡片判断是否显示手动按钮） */
  failed: boolean
}

/** 返回今天往回 days 天的本地日期 YYYY-MM-DD。 */
function daysAgoLocalDate(days: number): string {
  const date = new Date()
  date.setDate(date.getDate() - days)
  const year = date.getFullYear()
  const month = String(date.getMonth() + 1).padStart(2, '0')
  const day = String(date.getDate()).padStart(2, '0')
  return `${year}-${month}-${day}`
}

/** 读取最近 7 天三餐/手记/情绪，拼成带角色指令与数据的饮食推荐用户消息。 */
export async function buildDietPrompt(): Promise<string> {
  const today = todayLocalDate()
  const weekAgo = daysAgoLocalDate(6)
  let meals: MealEntry[] = []
  let moods: MoodEntry[] = []
  let notes: DailyNote[] = []
  try {
    meals = await apiClient.listMealEntries({ from: weekAgo, to: today })
  } catch { meals = [] }
  try {
    moods = await apiClient.listMoodEntries({ from: weekAgo, to: today })
  } catch { moods = [] }
  try {
    notes = (await apiClient.listDailyNotes()).filter(note => note.entryDate >= weekAgo && note.entryDate <= today)
  } catch { notes = [] }
  const mealLines = meals
    .sort((a, b) => a.entryDate.localeCompare(b.entryDate) || a.mealType.localeCompare(b.mealType))
    .map(m => `- ${m.entryDate} ${mealTypeLabel(m.mealType)}：${m.content ? m.content : '(无)'}${m.feeling ? `（感受 ${m.feeling}/5）` : ''}`)
  const moodLines = moods
    .sort((a, b) => a.entryDate.localeCompare(b.entryDate))
    .map(m => `- ${m.entryDate}：情绪 ${m.moodLevel}/5${m.content ? '｜' + m.content : ''}`)
  const noteLines = notes
    .sort((a, b) => a.entryDate.localeCompare(b.entryDate))
    .map(n => `- ${n.entryDate}：${n.content.replace(/\s+/g, ' ').slice(0, 120)}`)
  const context = [
    '以下是我最近 7 天（' + weekAgo + ' 至 ' + today + '）的一日三餐记录：'
    + (mealLines.length ? '\n' + mealLines.join('\n') : '（没有三餐记录）'),
    '以及情绪记录：'
    + (moodLines.length ? '\n' + moodLines.join('\n') : '（没有情绪记录）'),
    '以及手记记录：'
    + (noteLines.length ? '\n' + noteLines.join('\n') : '（没有手记记录）'),
  ].join('\n')
  return DIET_PROMPT + '\n\n' + context
}

function mealTypeLabel(type: string): string {
  if (type === 'breakfast') return '早餐'
  if (type === 'lunch') return '午餐'
  if (type === 'dinner') return '晚餐'
  return type
}

/** 内部：消费流式接口并落库，返回是否成功写入。onToken 用于流式预览（每收到 token 回调当前已生成全文）。 */
async function collectStream(controller: AbortController, onToken?: (text: string) => void): Promise<{ ok: boolean; aborted: boolean }> {
  let ok = false
  let aborted = false
  let output = ''
  const today = todayLocalDate()
  try {
    const messages = [{ role: 'user' as const, content: await buildDietPrompt() }]
    for await (const event of apiClient.streamExperimentalAiChatEphemeral(messages, controller.signal)) {
      if (controller.signal.aborted) { aborted = true; break }
      if (event.type === 'token') {
        output += event.content
        onToken?.(output)
      }
      if (event.type === 'incomplete' || event.type === 'error') { ok = false; break }
    }
    if (!aborted && output.trim()) {
      await apiClient.upsertDailyDietRecommendation(today, output.trim())
      ok = true
    }
  } catch (cause) {
    if (cause instanceof Error && cause.name === 'AbortError') aborted = true
    else if (!isApiClientAbort(cause)) { ok = false }
  }
  return { ok, aborted }
}

/**
 * 检查当天无推荐且跨了新的一天 → 自动生成一次。
 * 首页卡片挂载与午夜定时器回调调用。
 */
export async function autoGenerateDailyDietIfNeeded(onToken?: (text: string) => void): Promise<DailyDietAutoResult> {
  const today = todayLocalDate()
  if (generateStartedRef.current && documentStartKey === today) return { generated: false, aiUnavailable: false, failed: false }
  try {
    const existing = await apiClient.getDailyDietRecommendation(today)
    if (existing) { writeLastSeenDate(today); return { generated: false, aiUnavailable: false, failed: false } }
  } catch {
    return { generated: false, aiUnavailable: false, failed: true }
  }
  generateStartedRef.current = true
  documentStartKey = today
  try {
    const status = await apiClient.getAiConfigStatus()
    if (!status.configured) { writeLastSeenDate(today); return { generated: false, aiUnavailable: true, failed: false } }
  } catch {
    return { generated: false, aiUnavailable: true, failed: false }
  }
  const controller = new AbortController()
  const result = await collectStream(controller, onToken)
  writeLastSeenDate(today)
  return { generated: result.ok, aiUnavailable: false, failed: !result.ok && !result.aborted }
}

/**
 * 手动强制生成（弹窗“重新生成”）：跳过幂等 guard 与已有检查，
 * 无论弹窗是否关闭都在后台持续生成，onToken 回调流式预览。
 */
export async function generateDailyDietNow(input: { signal: AbortSignal; onToken?: (text: string) => void }): Promise<DailyDietAutoResult> {
  const today = todayLocalDate()
  try {
    const status = await apiClient.getAiConfigStatus()
    if (!status.configured) return { generated: false, aiUnavailable: true, failed: false }
  } catch {
    return { generated: false, aiUnavailable: true, failed: false }
  }
  generateStartedRef.current = true
  documentStartKey = today
  const controller = new AbortController()
  const onAbort = () => controller.abort()
  input.signal.addEventListener('abort', onAbort, { once: true })
  const result = await collectStream(controller, input.onToken)
  input.signal.removeEventListener('abort', onAbort)
  writeLastSeenDate(today)
  return { generated: result.ok, aiUnavailable: false, failed: !result.ok && !result.aborted }
}

export function resetDailyDietAutoGenerateGuard(): void {
  generateStartedRef.current = false
}

export { DIET_PROMPT, startMidnightAutoGenerate }
