import { existsSync, readFileSync, statSync } from 'node:fs'
import { describe, expect, it } from 'vitest'

const mascotSource = readFileSync(new URL('../apps/client/src/pages/index/experimental-ai/components/experimental-ai-mascot.tsx', import.meta.url), 'utf8')
const indexSource = readFileSync(new URL('../apps/client/src/pages/index/experimental-ai/index.tsx', import.meta.url), 'utf8')
const styleSource = readFileSync(new URL('../apps/client/src/pages/index/index.scss', import.meta.url), 'utf8')
const assetPath = new URL('../apps/client/src/assets/mascot/mr-help.riv', import.meta.url)
const currentAssetPath = new URL('../apps/client/src/assets/mascot/ipip-character.riv', import.meta.url)

describe('Mr Help Rive mascot contract', () => {
  it('keeps the H5 Rive asset and state machine isolated', () => {
    expect(existsSync(assetPath)).toBe(true)
    expect(statSync(assetPath).size).toBeGreaterThan(0)
    expect(existsSync(currentAssetPath)).toBe(true)
    expect(statSync(currentAssetPath).size).toBeGreaterThan(0)
    expect(mascotSource).toContain("@rive-app/react-canvas")
    expect(mascotSource).toContain("State Machine 1")
    expect(mascotSource).toContain("'Speak'")
    expect(mascotSource).toContain("'Happy'")
    expect(mascotSource).toContain("'Wrong'")
    expect(mascotSource).toContain('StateMachineInputType.Trigger')
    expect(mascotSource).toContain('StateMachineInputType.Boolean')
    expect(mascotSource).toContain('StateMachineInputType.Number')
    expect(mascotSource).toContain('stateMachineInputs')
    expect(mascotSource).toContain('interactionNonce')
    expect(mascotSource).toContain('triggerInputs')
    expect(mascotSource).toContain('Math.random() * triggerInputs.length')
  })

  it('has DPR layout, cleanup, SVG fallback, and key-node-only mounts', () => {
    expect(mascotSource).toContain('Fit.Contain')
    expect(mascotSource).toContain('Alignment.Center')
    expect(mascotSource).toContain('useDevicePixelRatio: true')
    expect(mascotSource).toContain('rive.cleanup()')
    expect(mascotSource).toContain('riveFailed')
    expect(indexSource).toContain('latestAssistantId')
    expect(indexSource).toContain('useRiveMascot generationId')
    expect(indexSource).toContain('experimental-ai-welcome-mascot')
    expect(indexSource).toContain('message.id === latestAssistantId && message.status === \'done\'')
    expect(indexSource).toContain('experimental-ai-message-is-latest')
    expect(indexSource).toContain('welcomeDismissing')
    expect(indexSource).toContain('setWelcomeDismissing(true)')
    expect(indexSource).not.toContain('hasMentorHeading')
    expect(styleSource).toContain('experimental-ai-markdown-mentor-end')
    expect(styleSource).toContain('position: absolute')
    expect(styleSource).toContain('padding-bottom: 34px')
    expect(styleSource).toContain('pointer-events: none')
    expect(styleSource).toContain('pointer-events: auto')
    expect(styleSource).toContain('display: flow-root')
    expect(styleSource).toContain('experimental-ai-welcome-mascot.is-dismissing')
    expect(indexSource).not.toContain('experimental-ai-assistant-avatar-slot"><ExperimentalAiMascot')
    expect(styleSource).toContain('experimental-ai-mascot-rive canvas')
    expect(styleSource).toContain('.experimental-ai-assistant-avatar-slot { display: none !important; }')
    expect(styleSource).toContain('.experimental-ai-mascot-shell.is-reacting')
    expect(styleSource).toContain('experimental-ai-mascot-react')
    expect(styleSource).toContain('@media (hover: hover)')
  })
})
