import { readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'
import { canModifyItemExplorationContext } from '../apps/client/src/pages/index/item-exploration-state'

const page = readFileSync(new URL('../apps/client/src/pages/index/index.tsx', import.meta.url), 'utf8')
const prototype = readFileSync(new URL('../apps/client/src/pages/index/exploration-prototype.tsx', import.meta.url), 'utf8')
const styles = readFileSync(new URL('../apps/client/src/pages/index/index.scss', import.meta.url), 'utf8')

describe('exploration H5 visual and refresh state', () => {
  it('keeps deleted and unavailable contexts read-only with the approved selector controls', () => {
    const track = { id: 'track-1', name: 'Deleted track', createdAt: '2026-07-26T00:00:00.000Z', updatedAt: '2026-07-26T00:00:00.000Z' }

    expect(canModifyItemExplorationContext({ status: 'track-deleted', itemId: 'item-1', track: { ...track, deletedAt: '2026-07-26T01:00:00.000Z' } }, 'abandoned')).toBe(false)
    expect(canModifyItemExplorationContext({ status: 'unavailable', itemId: 'item-1', trackId: 'missing-track' }, 'abandoned')).toBe(false)
    expect(canModifyItemExplorationContext({ status: 'available', itemId: 'item-1', track }, 'abandoned')).toBe(false)
    expect(canModifyItemExplorationContext({ status: 'no-association', itemId: 'item-1' }, 'abandoned')).toBe(false)
    expect(canModifyItemExplorationContext({ status: 'available', itemId: 'item-1', track }, 'idea_to_try')).toBe(true)
    expect(canModifyItemExplorationContext({ status: 'no-association', itemId: 'item-1' }, 'idea_to_try')).toBe(true)
    expect(page).toContain("className='item-exploration-actions'")
    expect(page).toContain("className='exploration-inline-button danger'")
    expect(page).toContain("className='exploration-inline-button item-exploration-selector-cancel'")
    expect(page).toContain('onClick={() => setExplorationSelectorOpen(false)}>')
    expect(page).toContain("className='item-exploration-copy muted'>未归入探索主线")
    expect(page).toContain('const canModifySelectedItemExploration = canModifyItemExplorationContext(itemExplorationContext, selectedItem?.status)')
    expect(page).toContain('if (!selectedId || !canModifySelectedItemExploration || itemExplorationSaving || itemExplorationUnknownOutcome) return')
    expect(page).toContain('{explorationSelectorOpen && canModifySelectedItemExploration &&')
    expect(page).toContain("const [startOverwriteConfirm, setStartOverwriteConfirm] = useState(false)")
    expect(page).toContain("const [startUnknownOutcome, setStartUnknownOutcome] = useState(false)")
    expect(page).toContain("requiresStartActionOverwriteConfirmation(item, submittedPrompt) && !overwriteExistingStartAction")
    expect(page).toContain("overwriteExistingStartAction: true")
    expect(page).toContain("确认覆盖并开始")
    expect(page).toContain("重新读取真实数据")
    expect(page).toContain("setStartOverwriteConfirm(false); setStartConfirmError('')")
    expect(page).toContain("[...refreshed.items, ...refreshed.trashItems].some((candidate) => candidate.id === item.id)")
    expect(styles).toContain('.item-exploration-selector-options')
    expect(styles).toContain('.item-exploration-copy.muted { color: #c1bbb2; }')
  })

  it('retains loaded exploration content during refreshes and module switches', () => {
    expect(prototype).toContain("{listLoading && listReadSucceeded && <Text className='exploration-refreshing'>正在更新…</Text>}")
    expect(prototype).toContain("{detailLoading && !history ? <View className='exploration-state'><Text>正在载入探索历史…</Text></View>")
    expect(prototype).toContain("{detailLoading && <Text className='exploration-refreshing'>正在更新…</Text>}")
    expect(prototype).not.toContain('TruncatedDisplayName')
    expect(prototype).not.toContain('ResizeObserver')
    expect(prototype).not.toContain('measureText')
    expect(prototype).toContain('const TrackItem = memo(function TrackItem')
    expect(prototype).toContain('const itemTimeFormatter = new Intl.DateTimeFormat')
    expect(prototype).toContain('setHistory(next); setDetailLoading(false)')
    expect(prototype).not.toContain('startTransition')
    expect(prototype).toContain('if (!resultApplied && isCurrentExplorationRequest(requestId, detailRequest.current)) setDetailLoading(false)')
    expect(prototype).toContain('const listReloaded = await loadList(false, track.id)')
    expect(prototype).toContain('if (listReloaded) { await loadHistory(track.id); await onItemsChanged() }')
    expect(prototype).toContain('await apiClient.deleteExplorationTrack(history.track.id); setConfirmDelete(false); await loadList(false); await onItemsChanged()')
    expect(page).toContain('const reloadCurrentItemExplorationContext = async () =>')
    expect(page).toContain('onItemsChanged={() => refresh().then(() => reloadCurrentItemExplorationContext()).then(() => undefined)}')
    expect(prototype).toContain('exploration-track-item-time')
    expect(prototype).toContain('exploration-create-modal-backdrop')
    expect(page).toContain("const [explorationMounted, setExplorationMounted] = useState(false)")
    expect(page).toContain("if (activeModule === 'explorations') setExplorationMounted(true)")
    expect(page).toContain('setExplorationFactsVersion((version) => version + 1)')
    expect((page.match(/setExplorationFactsVersion\(\(version\) => version \+ 1\)/g) ?? []).length).toBe(8)
    expect(page).toContain('const context = await application.assignItemToExplorationTrack(selectedId, trackId)\n      setItemExplorationContext(context)\n      setExplorationFactsVersion((version) => version + 1)')
    expect(page).toContain("await application.removeItemFromExplorationTrack(selectedId)\n      setItemExplorationContext({ status: 'no-association', itemId: selectedId })\n      setExplorationFactsVersion((version) => version + 1)")
    expect(page).toContain('await application.changeStatus(selectedItem.id, action.status)\n      await refresh(selectedItem.id)\n      setExplorationFactsVersion((version) => version + 1)')
    expect(page).toContain('await application.deleteItem(selectedItem.id)')
    expect(page).toContain('await refresh(undefined)\n      setExplorationFactsVersion((version) => version + 1)')
    expect(page).toContain('await refresh(restored.id)\n      setExplorationFactsVersion((version) => version + 1)')
    expect(page).toContain('explorationFactsVersion={explorationFactsVersion}')
    expect(prototype).toContain('useEffect(() => { if (explorationFactsVersion > 0 && selectedId) void loadHistory(selectedId) }, [explorationFactsVersion])')
    expect(styles).toContain('.exploration-module-retained-hidden { display: none; }')
    expect(styles).toContain('.exploration-detail-panel { scrollbar-gutter: stable; }')
    expect(styles).toContain('.exploration-detail { width: min(100%, 760px); margin: 0 auto; }')
    expect(styles).toContain('.exploration-list-heading > view > text:last-child')
    expect(styles).toContain('text-overflow: ellipsis')
    expect(styles).toContain('.exploration-track-item-title { overflow: hidden; min-width: 0; flex: 0 1 auto; max-width: 45%;')
    expect(styles).not.toContain('content-visibility: auto')
    expect(styles).toContain('white-space: nowrap')
  })

  it('keeps the methods workbench as a soft two-column desktop workspace and single-column on small screens', () => {
    expect(styles).toContain('.methods-panel { width: 100%; max-width: none; margin: 0; padding: 0; border: 0; border-radius: 0; background: transparent; box-shadow: none; }')
    expect(styles).not.toContain('.methods-panel > view:first-child')
    expect(page).toContain("className='methods-page-header'")
    expect(styles).toContain('.methods-page-header { display: flex; align-items: flex-end; justify-content: space-between; box-sizing: border-box; width: 100%;')
    expect(styles).toContain('.methods-workbench { display: grid; box-sizing: border-box; width: 100%; min-width: 0; grid-template-columns: minmax(0, 34%) minmax(0, 66%)')
    expect(styles).toContain('height: clamp(660px, calc(150dvh - 330px), 840px)')
    expect(styles).toContain('border-radius: 18px; background: #fffdf9; box-shadow: 0 10px 30px')
    expect(styles).toContain('.method-history-button, .method-evidence-button { display: flex; align-items: center; justify-content: flex-start;')
    expect(styles).toContain('.method-list-pane { display: flex; min-height: 0; padding: 18px; overflow-y: auto; overscroll-behavior: contain; flex-direction: column;')
    expect(styles).toContain('border-right: 1px solid #ded8cd; background: #fffdf9;')
    expect(styles).toContain('.method-list { display: flex; min-height: 0; margin-top: 10px; flex-direction: column; }')
    expect(styles).toContain('.method-detail-pane { min-width: 0; overflow-y: auto; background: #fffdf9; }')
    expect(styles).toContain('.method-apply-button, .method-action-submit { display: flex; align-items: center; justify-content: center; box-sizing: border-box; width: 100%; height: 42px; margin-top: 16px; padding: 0 14px; overflow: hidden; border-radius: 999px;')
    expect(styles).toContain('.methods-workbench { grid-template-columns: 1fr; height: auto; }')
  })

  it('keeps the shared history heading at the exploration history weight', () => {
    expect(styles).toContain('.exploration-section-title { display: block; margin-bottom: 10px; color: #443f38; font-size: 17px; font-weight: 800; }')
    expect(styles).toContain('.exploration-history-heading { display: flex; align-items: center; justify-content: space-between; gap: 12px; }')
  })

  it('switches the two history views in one list area and resets on track changes', () => {
    expect(prototype).toContain("const [historyView, setHistoryView] = useState<'history' | 'abandoned'>('history')")
    expect(prototype).toContain("useEffect(() => { setHistoryView('history'); if (selectedId) void loadHistory(selectedId) }, [selectedId])")
    expect(prototype).toContain("const visibleHistory = historyView === 'history' ? history?.history : history?.abandonedHistory")
    expect(prototype).toContain("className='exploration-history-heading'")
    expect(prototype).toContain("onClick={() => setHistoryView((view) => view === 'history' ? 'abandoned' : 'history')}")
    expect(prototype).toContain("{historyView === 'history' ? '当前还没有可回看的探索历史。' : '当前还没有已放弃记录。'}")
    expect(prototype).not.toContain('const [abandonedOpen, setAbandonedOpen]')
    expect(styles).toContain('.exploration-history-heading { display: flex; align-items: center; justify-content: space-between; gap: 12px; }')
  })

  it('keeps the desktop exploration workspace at the approved expanded height', () => {
    expect(styles).toContain('.exploration-workspace { display: grid; grid-template-columns: minmax(280px, 340px) minmax(0, 1fr); height: 816px;')
    expect(styles).toContain('.exploration-workspace { display: block; height: auto;')
  })

  it('centers the delete confirmation and cancels only when its backdrop is clicked', () => {
    expect(prototype).toContain("{confirmDelete && <View className='exploration-confirm-backdrop' onClick={() => setConfirmDelete(false)}>")
    expect(prototype).toContain("className='exploration-confirm' role='dialog' aria-label='删除主线确认' onClick={(event) => event.stopPropagation()}")
    expect(prototype).toContain("{confirmRestore && <View className='exploration-confirm-corner'>")
    expect(styles).toContain('.exploration-confirm-backdrop { position: fixed; z-index: 45; inset: 0; display: flex; align-items: center; justify-content: center;')
    expect(styles).toContain('.exploration-confirm-corner { position: fixed; z-index: 45; right: 24px; bottom: 24px;')
    expect(styles).not.toContain('.exploration-confirm { position: fixed;')
  })

  it('requires an explicit confirmation before restoring a trash entry', () => {
    expect(page).toContain("const [pendingTrashRestore, setPendingTrashRestore] = useState<TrashEntry>()")
    expect(page).toContain('onClick={() => setPendingTrashRestore(entry)}>恢复</Button>')
    expect(page).toContain("{pendingTrashRestore && <View className='trash-restore-backdrop' onClick={() => { if (!busy) setPendingTrashRestore(undefined) }}>")
    expect(page).toContain("className='trash-restore-confirm' role='dialog' aria-label='恢复确认' onClick={(event) => event.stopPropagation()}")
    expect(page).toContain('onClick={() => restoreTrashEntry(pendingTrashRestore)}>恢复</Button>')
    expect(page).toContain('setPendingTrashRestore(undefined)')
    expect(styles).toContain('.trash-restore-backdrop { position: fixed; z-index: 50; inset: 0; display: flex; align-items: center; justify-content: center;')
  })
})
