import { readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'
import { canModifyItemExplorationContext } from '../apps/client/src/pages/index/item-exploration-state'

const page = readFileSync(new URL('../apps/client/src/pages/index/index.tsx', import.meta.url), 'utf8')
const prototype = readFileSync(new URL('../apps/client/src/pages/index/exploration-prototype.tsx', import.meta.url), 'utf8')
const styles = readFileSync(new URL('../apps/client/src/pages/index/index.scss', import.meta.url), 'utf8')

describe('exploration H5 visual and refresh state', () => {
  it('uses one viewport-bound desktop scroll container so short modules do not create duplicate page scrollbars', () => {
    expect(styles).toContain('@media (min-width: 981px) {')
    expect(styles).toContain('html, body, #app, .app-shell { height: 100%; overflow: clip; }')
    expect(styles).toContain('.app-main { box-sizing: border-box; height: 100dvh; min-height: 0; margin-left: 220px; overflow-y: auto; }')
  })

  it('keeps deleted and unavailable contexts read-only with the approved selector controls', () => {
    const track = { id: 'track-1', name: 'Deleted track', createdAt: '2026-07-26T00:00:00.000Z', updatedAt: '2026-07-26T00:00:00.000Z' }

    expect(canModifyItemExplorationContext({ status: 'track-deleted', itemId: 'item-1', track: { ...track, deletedAt: '2026-07-26T01:00:00.000Z' } }, 'abandoned')).toBe(false)
    expect(canModifyItemExplorationContext({ status: 'unavailable', itemId: 'item-1', trackId: 'missing-track' }, 'abandoned')).toBe(false)
    expect(canModifyItemExplorationContext({ status: 'available', itemId: 'item-1', track }, 'abandoned')).toBe(false)
    expect(canModifyItemExplorationContext({ status: 'no-association', itemId: 'item-1' }, 'abandoned')).toBe(false)
    expect(canModifyItemExplorationContext({ status: 'available', itemId: 'item-1', track }, 'idea_to_try')).toBe(true)
    expect(canModifyItemExplorationContext({ status: 'no-association', itemId: 'item-1' }, 'idea_to_try')).toBe(true)
    expect(page).toContain("className='item-exploration-actions'")
    expect(page).toContain("className='exploration-inline-button danger'")
    expect(page).toContain("className='exploration-inline-button item-exploration-selector-cancel'")
    expect(page).toContain('onClick={() => setExplorationSelectorOpen(false)}>')
    expect(page).toContain("className='item-exploration-copy muted'>未归入探索主线")
    expect(page).toContain('const canModifySelectedItemExploration = canModifyItemExplorationContext(itemExplorationContext, selectedItem?.status)')
    expect(page).toContain('if (!selectedId || !canModifySelectedItemExploration || itemExplorationSaving || itemExplorationUnknownOutcome) return')
    expect(page).toContain('{explorationSelectorOpen && canModifySelectedItemExploration &&')
    expect(page).toContain("const [startOverwriteConfirm, setStartOverwriteConfirm] = useState(false)")
    expect(page).toContain("const [startUnknownOutcome, setStartUnknownOutcome] = useState(false)")
    expect(page).toContain("requiresStartActionOverwriteConfirmation(item, submittedPrompt) && !overwriteExistingStartAction")
    expect(page).toContain("overwriteExistingStartAction: true")
    expect(page).toContain("确认覆盖并开始")
    expect(page).toContain("重新读取真实数据")
    expect(page).toContain("setStartOverwriteConfirm(false); setStartConfirmError('')")
    expect(page).toContain("[...refreshed.items, ...refreshed.trashItems].some((candidate) => candidate.id === item.id)")
    expect(styles).toContain('.item-exploration-selector-options')
    expect(styles).toContain('.item-exploration-copy.muted { color: #c1bbb2; }')
  })

  it('retains loaded exploration content during refreshes and module switches', () => {
    expect(prototype).toContain("{listLoading && listReadSucceeded && <Text className='exploration-refreshing'>正在更新…</Text>}")
    expect(prototype).toContain("{detailLoading && !history ? <View className='exploration-state'><Text>正在载入探索历史…</Text></View>")
    expect(prototype).toContain("{detailLoading && <Text className='exploration-refreshing'>正在更新…</Text>}")
    expect(prototype).not.toContain('TruncatedDisplayName')
    expect(prototype).not.toContain('ResizeObserver')
    expect(prototype).not.toContain('measureText')
    expect(prototype).toContain('const TrackItem = memo(function TrackItem')
    expect(prototype).toContain('const itemTimeFormatter = new Intl.DateTimeFormat')
    expect(prototype).toContain('setHistory(next); setDetailLoading(false)')
    expect(prototype).not.toContain('startTransition')
    expect(prototype).toContain('if (!resultApplied && isCurrentExplorationRequest(requestId, detailRequest.current)) setDetailLoading(false)')
    expect(prototype).toContain('await apiClient.deleteExplorationTrack(history.track.id); setConfirmDelete(false); await loadList(undefined, true); await onItemsChanged()')
    expect(page).toContain('const reloadCurrentItemExplorationContext = async () =>')
    expect(page).toContain('onItemsChanged={() => refresh().then(() => reloadCurrentItemExplorationContext()).then(() => undefined)}')
    expect(prototype).toContain('exploration-track-item-time')
    expect(prototype).toContain('exploration-create-modal-backdrop')
    expect(page).toContain("const [explorationMounted, setExplorationMounted] = useState(false)")
    expect(page).toContain("if (activeModule === 'explorations' || activeModule === 'settings') setExplorationMounted(true)")
    expect(page).toContain('setExplorationFactsVersion((version) => version + 1)')
    expect((page.match(/setExplorationFactsVersion\(\(version\) => version \+ 1\)/g) ?? []).length).toBe(8)
    expect(page).toMatch(/const context = await application\.assignItemToExplorationTrack\(selectedId, trackId\)\s+setItemExplorationContext\(context\)\s+setExplorationFactsVersion\(\(version\) => version \+ 1\)/)
    expect(page).toMatch(/await application\.removeItemFromExplorationTrack\(selectedId\)\s+setItemExplorationContext\(\{ status: 'no-association', itemId: selectedId \}\)\s+setExplorationFactsVersion\(\(version\) => version \+ 1\)/)
    expect(page).toMatch(/await application\.changeStatus\(changedItemId, action\.status\)\s+const refreshed = await refresh\(changedItemId\)/)
    expect(page).toContain('await application.deleteItem(selectedItem.id)')
    expect(page).toMatch(/await refresh\(undefined\)\s+setExplorationFactsVersion\(\(version\) => version \+ 1\)/)
    expect(page).toMatch(/await refresh\(restored\.id\)\s+setExplorationFactsVersion\(\(version\) => version \+ 1\)/)
    expect(page).toContain('explorationFactsVersion={explorationFactsVersion}')
    expect(prototype).toContain('const listConfirmed = await loadList(selectedId, false, true)')
    expect(prototype).toContain('if (!listConfirmed.succeeded || !confirmedId || selectedIdRef.current !== confirmedId) return')
    expect(prototype).toContain('await loadHistory(confirmedId)')
    expect(prototype).toContain('const effectivePreferredId = preserveCurrentSelection ? selectedIdRef.current : preferredId')
    expect(styles).toContain('.exploration-module-retained-hidden { display: none; }')
    expect(styles).toContain('.exploration-detail-panel { scrollbar-gutter: stable; }')
    expect(styles).toContain('.app-main:has(.settings-module) { overflow-y: auto; }')
    expect(styles).toContain('.exploration-detail { width: min(100%, 760px); margin: 0 auto; }')
    expect(styles).toContain('.exploration-list-heading > view > text:last-child')
    expect(styles).toContain('text-overflow: ellipsis')
    expect(styles).toContain('.exploration-track-item-title { overflow: hidden; min-width: 0; flex: 0 1 auto; max-width: 45%;')
    expect(styles).not.toContain('content-visibility: auto')
    expect(styles).toContain('white-space: nowrap')
  })

  it('keeps the methods workbench as a soft two-column desktop workspace and single-column on small screens', () => {
    expect(styles).toContain('.methods-panel { width: 100%; max-width: none; margin: 0; padding: 0; border: 0; border-radius: 0; background: transparent; box-shadow: none; }')
    expect(styles).not.toContain('.methods-panel > view:first-child')
    expect(page).toContain("className='methods-page-header'")
    expect(styles).toContain('.methods-page-header { display: flex; align-items: flex-end; justify-content: space-between; box-sizing: border-box; width: 100%;')
    expect(styles).toContain('.methods-workbench { display: grid; box-sizing: border-box; width: 100%; min-width: 0; grid-template-columns: minmax(0, 34%) minmax(0, 66%)')
    expect(styles).toContain('height: clamp(660px, calc(150dvh - 330px), 840px)')
    expect(styles).toContain('border-radius: 18px; background: #fffdf9; box-shadow: 0 10px 30px')
    expect(styles).toContain('.method-history-button, .method-evidence-button { display: flex; align-items: center; justify-content: flex-start;')
    expect(styles).toContain('.method-list-pane { display: flex; min-height: 0; padding: 18px; overflow-y: auto; overscroll-behavior: contain; flex-direction: column;')
    expect(styles).toContain('border-right: 1px solid #ded8cd; background: #fffdf9;')
    expect(styles).toContain('.method-list { display: flex; min-height: 0; margin-top: 10px; flex-direction: column; }')
    expect(styles).toContain('.method-detail-pane { min-width: 0; overflow-y: auto; background: #fffdf9; }')
    expect(styles).toContain('.method-apply-button, .method-action-submit { display: flex; align-items: center; justify-content: center; box-sizing: border-box; width: 100%; height: 42px; margin-top: 16px; padding: 0 14px; overflow: hidden; border-radius: 999px;')
    expect(styles).toContain('.methods-workbench { grid-template-columns: 1fr; height: auto; }')
    expect(styles).toContain('.method-list-title { overflow: hidden; color: #38332d; font-size: 15px; font-weight: 800; text-overflow: ellipsis; white-space: nowrap; }')
  })

  it('uses literal three dots when an action-pool title overflows', () => {
    expect(page).toContain("className='item-title'>{item.title}</Text>")
    expect(styles).toContain(".item-title { font-size: 16px; font-weight: 720; line-height: 22px; text-overflow: '...'; }")
  })

  it('keeps the shared history heading at the exploration history weight', () => {
    expect(styles).toContain('.exploration-section-title { display: block; margin-bottom: 10px; color: #443f38; font-size: 17px; font-weight: 800; }')
    expect(styles).toContain('.exploration-history-heading { display: flex; align-items: center; justify-content: space-between; gap: 12px; }')
  })

  it('switches the two history views in one list area and resets on track changes', () => {
    expect(prototype).toContain("const [historyView, setHistoryView] = useState<'history' | 'abandoned'>('history')")
    expect(prototype).toContain("setHistoryView('history')")
    expect(prototype).toContain('restoredHistoryIdRef.current === selectedId')
    expect(prototype).toContain("const visibleHistory = historyView === 'history' ? history?.history : history?.abandonedHistory")
    expect(prototype).toContain("className='exploration-history-heading'")
    expect(prototype).toContain("{history.abandonedHistory.length > 0 && <Button className='exploration-inline-button exploration-history-toggle'")
    expect(prototype).toContain("onClick={() => setHistoryView((view) => view === 'history' ? 'abandoned' : 'history')}")
    expect(prototype).toContain("{historyView === 'history' ? '当前还没有可回看的探索历史。' : '当前还没有已放弃记录。'}")
    expect(prototype).not.toContain('const [abandonedOpen, setAbandonedOpen]')
    expect(styles).toContain('.exploration-history-heading { display: flex; align-items: center; justify-content: space-between; gap: 12px; }')
  })

  it('keeps the desktop exploration workspace at the approved expanded height', () => {
    expect(styles).toContain('.exploration-workspace { display: grid; grid-template-columns: minmax(280px, 340px) minmax(0, 1fr); height: 816px;')
    expect(styles).toContain('.exploration-workspace { display: block; height: auto;')
  })

  it('paginates the left exploration list locally without making it independently scrollable', () => {
    expect(prototype).toContain('const EXPLORATION_TRACK_PAGE_SIZE = 9')
    expect(prototype).toContain('const [listPage, setListPage] = useState(1)')
    expect(prototype).toContain('const next = await apiClient.listExplorationTracks(controller.signal)')
    expect(prototype).toContain('const visibleTracks = tracks.slice((listPage - 1) * EXPLORATION_TRACK_PAGE_SIZE, listPage * EXPLORATION_TRACK_PAGE_SIZE)')
    expect(prototype).toContain('setSelectedId(nextTrack.track.id)')
    expect(prototype).toContain("{listPageCount > 1 && <View className='exploration-list-pagination'>")
    expect(prototype).not.toContain('listDeletedExplorationTracks')
    expect(prototype).not.toContain('exploration-deleted-entry')
    expect(styles).toContain('.exploration-list-panel { display: flex; overflow: hidden; flex-direction: column;')
    expect(styles).toContain('.exploration-track-list { display: flex; flex-direction: column; gap: 4px; margin-top: 30px; }')
    expect(styles).toContain('.exploration-list-pagination { display: flex; align-items: center; justify-content: space-between;')
    expect(prototype).toContain("className={`exploration-inline-button ${listPage === 1 ? 'is-disabled' : ''}`} disabled={listPage === 1}")
    expect(prototype).toContain("if (listPage > 1) changeListPage(listPage - 1)")
    expect(prototype).toContain("if (listPage < listPageCount) changeListPage(listPage + 1)")
    expect(styles).toContain('.exploration-list-pagination .exploration-inline-button.is-disabled')
    expect(styles).toContain('taro-button-core.exploration-inline-button[disabled="true"]')
    expect(styles).toContain('.exploration-prototype taro-button-core.exploration-inline-button { width: auto !important;')
    expect(styles).toContain('.exploration-list-heading .section-kicker { display: none; }')
    expect(styles).toContain('.exploration-track-row { display: flex; box-sizing: border-box; min-height: 68px;')
  })

  it('centers the delete confirmation and cancels only when its backdrop is clicked', () => {
    expect(prototype).toContain("{confirmDelete && <View className='exploration-confirm-backdrop' onClick={() => setConfirmDelete(false)}>")
    expect(prototype).toContain("className='exploration-confirm' role='dialog' aria-label='删除主线确认' onClick={(event) => event.stopPropagation()}")
    expect(styles).toContain('.exploration-confirm-backdrop { position: fixed; z-index: 45; inset: 0; display: flex; align-items: center; justify-content: center;')
    expect(styles).not.toContain('.exploration-confirm { position: fixed;')
  })

  it('requires an explicit confirmation before restoring a trash entry', () => {
    expect(page).toContain("const [pendingTrashRestore, setPendingTrashRestore] = useState<TrashEntry>()")
    expect(page).toContain('onClick={() => setPendingTrashRestore(entry)}>恢复</Button>')
    expect(page).toContain("{pendingTrashRestore && <View className='trash-restore-backdrop' onClick={() => { if (!busy) setPendingTrashRestore(undefined) }}>")
    expect(page).toContain("className='trash-restore-confirm' role='dialog' aria-label='恢复确认' onClick={(event) => event.stopPropagation()}")
    expect(page).toContain('onClick={() => restoreTrashEntry(pendingTrashRestore)}>恢复</Button>')
    expect(page).toContain('setPendingTrashRestore(undefined)')
    expect(styles).toContain('.trash-restore-backdrop { position: fixed; z-index: 50; inset: 0; display: flex; align-items: center; justify-content: center;')
  })

  it('paginates trash entries locally in groups of eight without changing restore requests', () => {
    expect(page).toContain('const TRASH_ENTRIES_PER_PAGE = 8')
    expect(page).toContain('const [trashPage, setTrashPage] = useState(1)')
    expect(page).toContain('const trashPageCount = Math.max(1, Math.ceil(trashEntries.length / TRASH_ENTRIES_PER_PAGE))')
    expect(page).toContain('const visibleTrashEntries = trashEntries.slice((trashPage - 1) * TRASH_ENTRIES_PER_PAGE, trashPage * TRASH_ENTRIES_PER_PAGE)')
    expect(page).toContain('onClick={() => { setTrashFilter(entry); setTrashPage(1) }}')
    expect(page).toContain('setTrashPage((page) => Math.min(page, Math.max(1, Math.ceil(entries.length / TRASH_ENTRIES_PER_PAGE))))')
    expect(page).toContain('{trashPageCount > 1 && <View className=\'pagination trash-pagination\'>')
    expect(page).toContain('if (trashPage > 1) setTrashPage((page) => page - 1)')
    expect(page).toContain('if (trashPage < trashPageCount) setTrashPage((page) => page + 1)')
    expect(page).toContain('visibleTrashEntries.map((entry)')
    expect(styles).toContain('.trash-pagination { grid-template-columns: auto auto auto; justify-content: center; gap: 8px; }')
    expect(styles).toContain('.trash-pagination .pagination-button { min-width: 52px; height: 30px; padding: 0 8px; }')
    expect(styles).toContain('.trash-pagination .pagination-button:last-child { justify-self: auto; }')
  })

  it('limits every H5 item-creation title to twenty Unicode graphemes without truncating content', () => {
    const segmenter = new Intl.Segmenter(undefined, { granularity: 'grapheme' })
    const count = (value: string) => [...segmenter.segment(value.trim())].length

    expect(count('中'.repeat(20))).toBe(20)
    expect(count('a'.repeat(21))).toBe(21)
    expect(count('👨‍👩‍👧‍👦'.repeat(20))).toBe(20)
    expect(count('中a👨‍👩‍👧‍👦'.repeat(7))).toBe(21)
    expect(page).toContain("const ITEM_TITLE_MAX_GRAPHEMES = 20")
    expect(page).toContain("new Intl.Segmenter(undefined, { granularity: 'grapheme' })")
    expect(page).toContain('function captureTitleCandidate(title: string, content: string): string')
    expect(page).toContain('if (!captureTitleWithinLimit) {')
    expect(page).toContain("value={title} placeholder='一句话记录你想做什么'")
    expect(page).toContain("<View className='item-title-input-wrap'><Input ref={captureInputRef}")
    expect(page).toContain("<Text className='item-title-counter'>{captureTitleGraphemes}/{ITEM_TITLE_MAX_GRAPHEMES}</Text></View>")
    expect(page).toContain("value={methodActionTitle} placeholder='这次具体要完成什么'")
    expect(page).toContain("<View className='item-title-input-wrap'><input className='method-action-input'")
    expect(page).toContain('methodActionTitleGraphemes}/{ITEM_TITLE_MAX_GRAPHEMES}')
    expect(prototype).toContain('const ITEM_TITLE_MAX_GRAPHEMES = 20')
    expect(prototype).toContain("new Intl.Segmenter(undefined, { granularity: 'grapheme' })")
    expect(prototype).toContain('if (!acceptsItemTitleInput(draft)) { setDraftTitleLimitReached(true); return }')
    expect(prototype).toContain("<View className='item-title-input-wrap'><Input className='exploration-capture-input'")
    expect(prototype).toContain("className='item-title-counter'>{itemTitleGraphemeCount(draft)}/{ITEM_TITLE_MAX_GRAPHEMES}</Text></View>")
    expect(prototype).toContain("className='item-title-limit-notice'>标题最多20个字符")
    expect(styles).toContain('.item-title-input-wrap { position: relative; }')
    expect(styles).toContain('.item-title-input-wrap .capture-modal-input, .item-title-input-wrap .exploration-capture-input, .item-title-input-wrap .method-action-input { padding-right: 50px; }')
    expect(styles).toContain('.item-title-counter { position: absolute;')
    expect(styles).toContain('color: #b5aea4;')
    expect(styles).toContain('.item-title-limit-notice { display: block;')
  })

  it('confirms backup restore only after all structured facts and exploration facts are read', () => {
    expect(page).toContain("const restoredTrashEntries = await trashApplication.listTrashEntries('all')")
    expect(page).toContain('const restoredFacts = await refresh(undefined, false)')
    expect(page).toContain('setItems(restoredFacts.items)')
    expect(page).toContain('setTrashEntries(restoredTrashEntries)')
    expect(page).toContain('setRestoreFactsVersion((version) => version + 1)')
    expect(page).toContain('await new Promise<void>((resolve, reject) => {')
    expect(page).toContain('onRestoreFactsConfirmed={() => restoreFactsConfirmationRef.current?.resolve()}')
    expect(page).toContain('setRestoring(!restoreFactsConfirmed)')
    expect(page).toContain("<View><Text>{activeExplorationTrackCount ?? '—'}</Text><Text>探索主线</Text></View>")
    expect(page).toContain("if (!restoredFacts.succeeded) throw new Error('恢复后的事项、方法或回收站读取未确认，请保留当前事实并重新读取。')")
    expect(prototype).toContain('const nextSelectedId = nextTracks[0]?.track.id')
    expect(prototype).toContain('let nextHistory: ExplorationTrackHistory | undefined')
    expect(prototype).toContain('setTracks(nextTracks)')
    expect(prototype).toContain('onRestoreFactsConfirmed()')
    expect(prototype).toContain("setDraft(''); setDraftTitleLimitReached(false)")
    expect(prototype).toContain("setEditing(false); setEditingTrackId(undefined); editingTrackIdRef.current = undefined")
    expect(prototype).toContain('onExplorationTrackCountChange(nextTracks.length)')
    expect(prototype).toContain("onRestoreFactsFailed('恢复后的探索主线读取失败，请保留当前事实并重新读取。')")
    expect(prototype).toContain("onRestoreFactsFailed('恢复后的探索历史读取失败，请保留当前事实并重新读取。')")
  })
})
