ALTER TABLE users ADD COLUMN updated_at DATETIME(3) NULL AFTER created_at;
ALTER TABLE user_sessions ADD COLUMN updated_at DATETIME(3) NULL AFTER created_at;
ALTER TABLE initial_owner_claims ADD COLUMN updated_at DATETIME(3) NULL AFTER created_at;
ALTER TABLE method_versions ADD COLUMN updated_at DATETIME(3) NULL AFTER created_at;
ALTER TABLE method_evidence ADD COLUMN updated_at DATETIME(3) NULL AFTER created_at;
ALTER TABLE method_applications ADD COLUMN updated_at DATETIME(3) NULL AFTER created_at;
ALTER TABLE item_status_events ADD COLUMN updated_at DATETIME(3) NULL AFTER created_at;
ALTER TABLE item_links ADD COLUMN updated_at DATETIME(3) NULL AFTER created_at;
ALTER TABLE security_audit_events ADD COLUMN updated_at DATETIME(3) NULL AFTER created_at;
ALTER TABLE user_roles ADD COLUMN updated_at DATETIME(3) NULL AFTER created_at;
ALTER TABLE system_metadata ADD COLUMN created_at DATETIME(3) NULL AFTER value;
ALTER TABLE method_tombstones ADD COLUMN created_at DATETIME(3) NULL AFTER title;
ALTER TABLE method_tombstones ADD COLUMN updated_at DATETIME(3) NULL AFTER created_at;

UPDATE users SET updated_at=created_at WHERE updated_at IS NULL;
UPDATE user_sessions SET updated_at=created_at WHERE updated_at IS NULL;
UPDATE initial_owner_claims SET updated_at=created_at WHERE updated_at IS NULL;
UPDATE method_versions SET updated_at=created_at WHERE updated_at IS NULL;
UPDATE method_evidence SET updated_at=created_at WHERE updated_at IS NULL;
UPDATE method_applications SET updated_at=created_at WHERE updated_at IS NULL;
UPDATE item_status_events SET updated_at=created_at WHERE updated_at IS NULL;
UPDATE item_links SET updated_at=created_at WHERE updated_at IS NULL;
UPDATE security_audit_events SET updated_at=created_at WHERE updated_at IS NULL;
UPDATE user_roles SET updated_at=created_at WHERE updated_at IS NULL;
UPDATE system_metadata SET created_at=updated_at WHERE created_at IS NULL;
UPDATE method_tombstones SET created_at=permanently_deleted_at WHERE created_at IS NULL;
UPDATE method_tombstones SET updated_at=permanently_deleted_at WHERE updated_at IS NULL;

ALTER TABLE users MODIFY COLUMN updated_at DATETIME(3) NOT NULL;
ALTER TABLE user_sessions MODIFY COLUMN updated_at DATETIME(3) NOT NULL;
ALTER TABLE initial_owner_claims MODIFY COLUMN updated_at DATETIME(3) NOT NULL;
ALTER TABLE method_versions MODIFY COLUMN updated_at DATETIME(3) NOT NULL;
ALTER TABLE method_evidence MODIFY COLUMN updated_at DATETIME(3) NOT NULL;
ALTER TABLE method_applications MODIFY COLUMN updated_at DATETIME(3) NOT NULL;
ALTER TABLE item_status_events MODIFY COLUMN updated_at DATETIME(3) NOT NULL;
ALTER TABLE item_links MODIFY COLUMN updated_at DATETIME(3) NOT NULL;
ALTER TABLE security_audit_events MODIFY COLUMN updated_at DATETIME(3) NOT NULL;
ALTER TABLE user_roles MODIFY COLUMN updated_at DATETIME(3) NOT NULL;
ALTER TABLE system_metadata MODIFY COLUMN created_at DATETIME(3) NOT NULL;
ALTER TABLE method_tombstones MODIFY COLUMN created_at DATETIME(3) NOT NULL;
ALTER TABLE method_tombstones MODIFY COLUMN updated_at DATETIME(3) NOT NULL;
