#!/bin/sh
set -eu

require_environment() {
  variable_name="$1"
  eval "variable_value=\${$variable_name:-}"
  if [ -z "$variable_value" ]; then
    echo "缺少 MySQL 权限收敛环境变量：$variable_name" >&2
    exit 1
  fi
}

for variable_name in \
  MYSQL_DATABASE MYSQL_UAT_DATABASE MYSQL_ROOT_PASSWORD \
  MYSQL_APP_USER MYSQL_APP_PASSWORD MYSQL_MIGRATOR_USER MYSQL_MIGRATOR_PASSWORD \
  UAT_MYSQL_APP_USER UAT_MYSQL_APP_PASSWORD UAT_MYSQL_MIGRATOR_USER UAT_MYSQL_MIGRATOR_PASSWORD
do
  require_environment "$variable_name"
done

if [ "$MYSQL_DATABASE" != 'knowledge_base' ] || [ "$MYSQL_UAT_DATABASE" != 'knowledge_base_uat' ]; then
  echo 'MySQL 数据库必须固定为 knowledge_base 与 knowledge_base_uat。' >&2
  exit 1
fi

for user in "$MYSQL_APP_USER" "$MYSQL_MIGRATOR_USER" "$UAT_MYSQL_APP_USER" "$UAT_MYSQL_MIGRATOR_USER"; do
  if [ "$user" = 'root' ]; then
    echo 'MySQL 业务用户不得使用 root。' >&2
    exit 1
  fi
done

if [ "$MYSQL_APP_USER" = "$MYSQL_MIGRATOR_USER" ] || \
  [ "$MYSQL_APP_USER" = "$UAT_MYSQL_APP_USER" ] || \
  [ "$MYSQL_APP_USER" = "$UAT_MYSQL_MIGRATOR_USER" ] || \
  [ "$MYSQL_MIGRATOR_USER" = "$UAT_MYSQL_APP_USER" ] || \
  [ "$MYSQL_MIGRATOR_USER" = "$UAT_MYSQL_MIGRATOR_USER" ] || \
  [ "$UAT_MYSQL_APP_USER" = "$UAT_MYSQL_MIGRATOR_USER" ]; then
  echo '日常与 UAT 的 app / migrator 必须为四个不同用户。' >&2
  exit 1
fi

mysql --protocol=socket --socket=/var/run/mysqld/mysqld.sock \
  -uroot -p"${MYSQL_ROOT_PASSWORD}" <<SQL
CREATE DATABASE IF NOT EXISTS \`${MYSQL_DATABASE}\`;
CREATE DATABASE IF NOT EXISTS \`${MYSQL_UAT_DATABASE}\`;

CREATE USER IF NOT EXISTS '${MYSQL_APP_USER}'@'%' IDENTIFIED BY '${MYSQL_APP_PASSWORD}';
CREATE USER IF NOT EXISTS '${MYSQL_MIGRATOR_USER}'@'%' IDENTIFIED BY '${MYSQL_MIGRATOR_PASSWORD}';
CREATE USER IF NOT EXISTS '${UAT_MYSQL_APP_USER}'@'%' IDENTIFIED BY '${UAT_MYSQL_APP_PASSWORD}';
CREATE USER IF NOT EXISTS '${UAT_MYSQL_MIGRATOR_USER}'@'%' IDENTIFIED BY '${UAT_MYSQL_MIGRATOR_PASSWORD}';
ALTER USER '${MYSQL_APP_USER}'@'%' IDENTIFIED BY '${MYSQL_APP_PASSWORD}';
ALTER USER '${MYSQL_MIGRATOR_USER}'@'%' IDENTIFIED BY '${MYSQL_MIGRATOR_PASSWORD}';
ALTER USER '${UAT_MYSQL_APP_USER}'@'%' IDENTIFIED BY '${UAT_MYSQL_APP_PASSWORD}';
ALTER USER '${UAT_MYSQL_MIGRATOR_USER}'@'%' IDENTIFIED BY '${UAT_MYSQL_MIGRATOR_PASSWORD}';

REVOKE ALL PRIVILEGES, GRANT OPTION FROM '${MYSQL_APP_USER}'@'%';
REVOKE ALL PRIVILEGES, GRANT OPTION FROM '${MYSQL_MIGRATOR_USER}'@'%';
REVOKE ALL PRIVILEGES, GRANT OPTION FROM '${UAT_MYSQL_APP_USER}'@'%';
REVOKE ALL PRIVILEGES, GRANT OPTION FROM '${UAT_MYSQL_MIGRATOR_USER}'@'%';

GRANT SELECT, INSERT, UPDATE, DELETE
  ON \`${MYSQL_DATABASE}\`.* TO '${MYSQL_APP_USER}'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, ALTER, DROP, INDEX, REFERENCES
  ON \`${MYSQL_DATABASE}\`.* TO '${MYSQL_MIGRATOR_USER}'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE
  ON \`${MYSQL_UAT_DATABASE}\`.* TO '${UAT_MYSQL_APP_USER}'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, ALTER, DROP, INDEX, REFERENCES
  ON \`${MYSQL_UAT_DATABASE}\`.* TO '${UAT_MYSQL_MIGRATOR_USER}'@'%';

DROP TABLE IF EXISTS \`${MYSQL_DATABASE}\`.\`mysql_m1_forbidden_create\`;
DROP TABLE IF EXISTS \`${MYSQL_UAT_DATABASE}\`.\`mysql_m1_forbidden_create\`;
FLUSH PRIVILEGES;

SHOW GRANTS FOR '${MYSQL_APP_USER}'@'%';
SHOW GRANTS FOR '${MYSQL_MIGRATOR_USER}'@'%';
SHOW GRANTS FOR '${UAT_MYSQL_APP_USER}'@'%';
SHOW GRANTS FOR '${UAT_MYSQL_MIGRATOR_USER}'@'%';
SQL
