import type { BackupData, BackupRepository, Item, ItemLink, ItemStatusEvent, Method, MethodApplication, MethodEvidence, MethodTombstone, MethodVersion, Review } from '@knowledge-base/contracts'
import { getRawDatabase, type SqliteKnowledgeDatabase } from './database'

type Row=Record<string,unknown>
const opt=(value:unknown)=>value==null?undefined:String(value)
const item=(r:Row):Item=>({id:String(r.id),title:String(r.title),content:String(r.content),status:r.status as Item['status'],createdAt:String(r.created_at),updatedAt:String(r.updated_at),...(opt(r.deleted_at)?{deletedAt:opt(r.deleted_at)}:{}),...(opt(r.start_action)?{startAction:opt(r.start_action)}:{})})
const review=(r:Row):Review=>({id:String(r.id),itemId:String(r.item_id),actualAction:String(r.actual_action),result:String(r.result),effective:String(r.effective),incompatible:String(r.incompatible),reason:String(r.reason),adjustment:String(r.adjustment),newIdeas:String(r.new_ideas),createdAt:String(r.created_at),updatedAt:String(r.updated_at)})
const method=(r:Row):Method=>({id:String(r.id),title:String(r.title),applicable:String(r.applicable),unsuitable:String(r.unsuitable),steps:String(r.steps),validationCount:Number(r.validation_count),version:Number(r.version),createdAt:String(r.created_at),updatedAt:String(r.updated_at),...(opt(r.deleted_at)?{deletedAt:opt(r.deleted_at)}:{})})
const version=(r:Row):MethodVersion=>({id:String(r.id),methodId:String(r.method_id),version:Number(r.version),title:String(r.title),applicable:String(r.applicable),unsuitable:String(r.unsuitable),steps:String(r.steps),...(opt(r.source_review_id)?{sourceReviewId:opt(r.source_review_id)}:{}),createdAt:String(r.created_at)})
const evidence=(r:Row):MethodEvidence=>({id:String(r.id),methodId:String(r.method_id),reviewId:String(r.review_id),createdAt:String(r.created_at),...(opt(r.relation)?{relation:r.relation as MethodEvidence['relation']}:{}),...(r.method_version==null?{}:{methodVersion:Number(r.method_version)})})
const app=(r:Row):MethodApplication=>({id:String(r.id),methodId:String(r.method_id),methodVersion:Number(r.method_version),itemId:String(r.item_id),createdAt:String(r.created_at)})
const event=(r:Row):ItemStatusEvent=>({id:String(r.id),itemId:String(r.item_id),...(opt(r.from_status)?{fromStatus:r.from_status as ItemStatusEvent['fromStatus']}:{}),toStatus:r.to_status as ItemStatusEvent['toStatus'],createdAt:String(r.created_at)})
const link=(r:Row):ItemLink=>({id:String(r.id),sourceReviewId:String(r.source_review_id),targetItemId:String(r.target_item_id),type:r.type as ItemLink['type'],createdAt:String(r.created_at)})
const tombstone=(r:Row):MethodTombstone=>({methodId:String(r.method_id),title:String(r.title),permanentlyDeletedAt:String(r.permanently_deleted_at),versions:JSON.parse(String(r.versions_json))})
export class SqliteBackupRepository implements BackupRepository {
 constructor(private readonly database:SqliteKnowledgeDatabase){} private get raw(){return getRawDatabase(this.database)}
 async exportData():Promise<BackupData>{return this.database.runInReadTransaction(()=>({items:(this.raw.prepare('SELECT * FROM items').all() as Row[]).map(item),reviews:(this.raw.prepare('SELECT * FROM reviews').all() as Row[]).map(review),methods:(this.raw.prepare('SELECT * FROM methods').all() as Row[]).map(method),methodEvidence:(this.raw.prepare('SELECT * FROM method_evidence').all() as Row[]).map(evidence),methodVersions:(this.raw.prepare('SELECT * FROM method_versions').all() as Row[]).map(version),methodApplications:(this.raw.prepare('SELECT * FROM method_applications').all() as Row[]).map(app),itemStatusEvents:(this.raw.prepare('SELECT * FROM item_status_events').all() as Row[]).map(event),itemLinks:(this.raw.prepare('SELECT * FROM item_links').all() as Row[]).map(link),methodTombstones:(this.raw.prepare('SELECT * FROM method_tombstones').all() as Row[]).map(tombstone)}))}
 async replaceData(data:BackupData):Promise<void>{this.database.runInTransaction(()=>{const r=this.raw;for(const table of ['item_links','item_status_events','method_applications','method_evidence','method_versions','method_tombstones','reviews','methods','items'])r.prepare(`DELETE FROM ${table}`).run();for(const x of data.items)r.prepare('INSERT INTO items VALUES(?,?,?,?,?,?,?,?)').run(x.id,x.title,x.content,x.status,x.createdAt,x.updatedAt,x.deletedAt??null,x.startAction??null);for(const x of data.itemStatusEvents)r.prepare('INSERT INTO item_status_events VALUES(?,?,?,?,?)').run(x.id,x.itemId,x.fromStatus??null,x.toStatus,x.createdAt);for(const x of data.reviews)r.prepare('INSERT INTO reviews VALUES(?,?,?,?,?,?,?,?,?,?,?)').run(x.id,x.itemId,x.actualAction,x.result,x.effective,x.incompatible,x.reason,x.adjustment,x.newIdeas,x.createdAt,x.updatedAt);for(const x of data.methods)r.prepare('INSERT INTO methods VALUES(?,?,?,?,?,?,?,?,?,?)').run(x.id,x.title,x.applicable,x.unsuitable,x.steps,x.validationCount,x.version,x.createdAt,x.updatedAt,x.deletedAt??null);for(const x of data.methodVersions)r.prepare('INSERT INTO method_versions VALUES(?,?,?,?,?,?,?,?,?)').run(x.id,x.methodId,x.version,x.title,x.applicable,x.unsuitable,x.steps,x.sourceReviewId??null,x.createdAt);for(const x of data.methodEvidence)r.prepare('INSERT INTO method_evidence VALUES(?,?,?,?,?,?)').run(x.id,x.methodId,x.reviewId,x.createdAt,x.relation??null,x.methodVersion??null);for(const x of data.methodApplications)r.prepare('INSERT INTO method_applications VALUES(?,?,?,?,?)').run(x.id,x.methodId,x.methodVersion,x.itemId,x.createdAt);for(const x of data.methodTombstones){if(!Array.isArray(x.versions)||x.versions.some(v=>!Number.isInteger(v.version)))throw new Error('无效的方法墓碑版本');r.prepare('INSERT INTO method_tombstones VALUES(?,?,?,?)').run(x.methodId,x.title,x.permanentlyDeletedAt,JSON.stringify(x.versions))}for(const x of data.itemLinks)r.prepare('INSERT INTO item_links VALUES(?,?,?,?,?)').run(x.id,x.sourceReviewId,x.targetItemId,x.type,x.createdAt);for(const x of data.methods)if(data.methodTombstones.some(t=>t.methodId===x.id))throw new Error('方法与墓碑不能并存')})}
}
