export type ItemErrorCode =
  | 'INVALID_ITEM_STATUS_TRANSITION'
  | 'ITEM_NOT_FOUND'
  | 'ITEM_NOT_IN_TRASH'
  | 'ITEM_TITLE_REQUIRED'
  | 'ITEM_TITLE_TOO_LONG'
  | 'ITEM_START_ACTION_ALREADY_EXISTS'
  | 'ITEM_METHOD_ALREADY_ASSOCIATED'
  | 'ITEM_NOT_REVIEWABLE'
