export type MethodErrorCode =
  | 'METHOD_REQUIRED_FIELDS_MISSING'
  | 'METHOD_NOT_FOUND'
  | 'METHOD_NOT_IN_TRASH'
  | 'METHOD_ALREADY_IN_TRASH'
  | 'METHOD_TOMBSTONE_ALREADY_EXISTS'
  | 'METHOD_VERSION_HISTORY_UNPROVABLE'
  | 'METHOD_ALREADY_VALIDATED_BY_REVIEW'
