import type { AiStreamEvent } from '@knowledge-base/contracts'
import { apiClient, isApiClientAbort } from '../../api-client'
import { todayLocalDate } from '../mood/mood-levels'

/**
 * 每日状态小结自动生成：跨天检测 + 幂等保护。
 * - 当天已有小结则不触发；
 * - AI 未配置则静默降级（不调用）；
 * - 生成失败不重试（避免重复消耗），返回 failed 供卡片显示手动按钮。
 */

const SUMMARY_PROMPT = '分析下我最近的状态'

const LAST_SEEN_DATE_KEY = 'marumaru.daily-summary.last-seen-date'
let documentStartKey = todayLocalDate()
const generateStartedRef = { current: false }

function writeLastSeenDate(date: string): void {
  try { localStorage.setItem(LAST_SEEN_DATE_KEY, date) } catch { /* ignore */ }
}

function setMidnightTimer(handler: () => void): number {
  const now = new Date()
  const next = new Date(now.getFullYear(), now.getMonth(), now.getDate() + 1, 0, 0, 1, 0)
  const delay = Math.max(1000, next.getTime() - now.getTime())
  return window.setTimeout(() => { handler(); setMidnightTimer(handler) }, delay)
}

export interface DailySummaryAutoResult {
  /** 本次是否真正调用并生成了内容（写入 daily_summaries） */
  generated: boolean
  /** 是否发现 AI 未配置（静默失败） */
  aiUnavailable: boolean
  /** 生成失败原因（不用于展示，仅卡片判断是否显示手动按钮） */
  failed: boolean
}

/** 内部：消费流式接口并落库，返回是否成功写入。onToken 用于流式预览（每收到 token 回调当前已生成全文）。 */
async function collectStream(controller: AbortController, onToken?: (text: string) => void): Promise<{ ok: boolean; aborted: boolean }> {
  let ok = false
  let aborted = false
  let output = ''
  const today = todayLocalDate()
  try {
    const messages = [{ role: 'user' as const, content: SUMMARY_PROMPT }]
    for await (const event of apiClient.streamExperimentalAiChatEphemeral(messages, controller.signal)) {
      if (controller.signal.aborted) { aborted = true; break }
      if (event.type === 'token') {
        output += event.content
        onToken?.(output)
      }
      if (event.type === 'incomplete' || event.type === 'error') { ok = false; break }
    }
    if (!aborted && output.trim()) {
      await apiClient.upsertDailySummary(today, output.trim())
      ok = true
    }
  } catch (cause) {
    if (cause instanceof Error && cause.name === 'AbortError') aborted = true
    else if (!isApiClientAbort(cause)) { ok = false }
  }
  return { ok, aborted }
}

/**
 * 检查当天无小结且跨了新的一天 → 自动生成一次。
 * 首页卡片挂载与午夜定时器回调调用。
 */
export async function autoGenerateDailySummaryIfNeeded(onToken?: (text: string) => void): Promise<DailySummaryAutoResult> {
  const today = todayLocalDate()
  // 同一天已生成过（页面开着跨午夜之外的重复挂载）不再触发
  if (generateStartedRef.current && documentStartKey === today) return { generated: false, aiUnavailable: false, failed: false }
  try {
    const existing = await apiClient.getDailySummary(today)
    if (existing) { writeLastSeenDate(today); return { generated: false, aiUnavailable: false, failed: false } }
  } catch {
    return { generated: false, aiUnavailable: false, failed: true }
  }
  generateStartedRef.current = true
  documentStartKey = today
  try {
    const status = await apiClient.getAiConfigStatus()
    if (!status.configured) { writeLastSeenDate(today); return { generated: false, aiUnavailable: true, failed: false } }
  } catch {
    return { generated: false, aiUnavailable: true, failed: false }
  }
  const controller = new AbortController()
  const result = await collectStream(controller, onToken)
  writeLastSeenDate(today)
  return { generated: result.ok, aiUnavailable: false, failed: !result.ok && !result.aborted }
}

/**
 * 手动强制生成（弹窗“重新生成”）：跳过幂等 guard 与已有检查，
 * 无论弹窗是否关闭都在后台持续生成，onToken 回调流式预览。
 */
export async function generateDailySummaryNow(input: { signal: AbortSignal; onToken?: (text: string) => void }): Promise<DailySummaryAutoResult> {
  const today = todayLocalDate()
  try {
    const status = await apiClient.getAiConfigStatus()
    if (!status.configured) return { generated: false, aiUnavailable: true, failed: false }
  } catch {
    return { generated: false, aiUnavailable: true, failed: false }
  }
  generateStartedRef.current = true
  documentStartKey = today
  const controller = new AbortController()
  const onAbort = () => controller.abort()
  input.signal.addEventListener('abort', onAbort, { once: true })
  const result = await collectStream(controller, input.onToken)
  input.signal.removeEventListener('abort', onAbort)
  writeLastSeenDate(today)
  return { generated: result.ok, aiUnavailable: false, failed: !result.ok && !result.aborted }
}

export function resetAutoGenerateGuard(): void {
  generateStartedRef.current = false
}

export function startMidnightAutoGenerate(handler: () => void): () => void {
  const timer = setMidnightTimer(handler)
  return () => window.clearTimeout(timer)
}

export { SUMMARY_PROMPT }
